apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - k8s.login.no
      secretName: whoami-tls
  rules:
    - host: k8s.login.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
