apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookstack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: bookstack-secrets
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: bookstack/APP_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: bookstack/DB_PASSWORD
    - secretKey: DB_ROOT_PASSWORD
      remoteRef:
        key: bookstack/DB_ROOT_PASSWORD
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: bookstack/OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: bookstack/OIDC_CLIENT_SECRET
