apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digitalocean-dns
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: digitalocean-dns
  data:
    - secretKey: token
      remoteRef:
        key: digitalocean/TOKEN
