apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-dns
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: ovh-dns
  data:
    - secretKey: OVH_APPLICATION_KEY
      remoteRef:
        key: external-dns/APPLICATION_KEY
    - secretKey: OVH_APPLICATION_SECRET
      remoteRef:
        key: external-dns/APPLICATION_SECRET
    - secretKey: OVH_CONSUMER_KEY
      remoteRef:
        key: external-dns/CONSUMER_KEY
