apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-dns
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: ovh-dns
  data:
    - secretKey: OVH_APPLICATION_KEY
      remoteRef:
        key: TekKom-Secret-K8s-Onprem/external-dns
        property: APPLICATION_KEY
    - secretKey: OVH_APPLICATION_SECRET
      remoteRef:
        key: TekKom-Secret-K8s-Onprem/external-dns
        property: APPLICATION_SECRET
    - secretKey: OVH_CONSUMER_KEY
      remoteRef:
        key: TekKom-Secret-K8s-Onprem/external-dns
        property: CONSUMER_KEY
