apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: ovh-credentials
  data:
    - secretKey: applicationKey
      remoteRef:
        key: cert-manager/APPLICATION_KEY
    - secretKey: applicationSecret
      remoteRef:
        key: cert-manager/APPLICATION_SECRET
    - secretKey: consumerKey
      remoteRef:
        key: cert-manager/CONSUMER_KEY
