apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beeformed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: beeformed
  data:
    - secretKey: AUTHENTIK_CLIENT_ID
      remoteRef:
        key: beeformed/AUTHENTIK_CLIENT_ID
    - secretKey: AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: beeformed/AUTHENTIK_CLIENT_SECRET
    - secretKey: SMTP_HOST
      remoteRef:
        key: beeformed/SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: beeformed/SMTP_PORT
    - secretKey: SMTP_USER
      remoteRef:
        key: beeformed/SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: beeformed/SMTP_PASSWORD
