apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: login

configMapGenerator:
  - name: beeformed-env
    literals:
      - NODE_ENV=production
      - TZ=Europe/Oslo
      - DB=beeformed
      - DB_USER=beeformed
      - DB_HOST=beeformed-db-rw
      - DB_PORT=5432
      - AUTH_URL=https://authentik.login.no
      - FRONTEND_URL=https://forms-next.login.no
      - API_URL=http://beeformed-api:8080/api
      - NEXT_PUBLIC_API_URL=https://forms-api-next.login.no/api
      - TRUST_PROXY=true
      - SMTP_SECURE=true
      - SMTP_FROM=noreply@login.no
      - SMTP_NAME=Login

images:
  - name: ghcr.io/login-linjeforeningen-for-it/beeformed/frontend
    newTag: sha-484214a
  - name: ghcr.io/login-linjeforeningen-for-it/beeformed/api
    newTag: sha-484214a
