apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: login

configMapGenerator:
  - name: beeformed-env
    literals:
      - NODE_ENV=production
      - TZ=Europe/Oslo
      - PORT=8080
      - DB=beeformed
      - DB_USER=beeformed
      - DB_HOST=beeformed-db-rw
      - DB_PORT=5432
      - NEXT_PUBLIC_API_URL=https://forms-api.login.no
      - AUTHENTIK_URL=https://authentik.login.no

images:
  - name: ghcr.io/login-linjeforeningen-for-it/beeformed/frontend
    newTag: sha-484214a
  - name: ghcr.io/login-linjeforeningen-for-it/beeformed/api
    newTag: sha-484214a
