apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: queenbee
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: queenbee
  data:
    - secretKey: AUTHENTIK_CLIENT_ID
      remoteRef:
        key: queenbee/AUTHENTIK_CLIENT_ID
    - secretKey: AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: queenbee/AUTHENTIK_CLIENT_SECRET
    - secretKey: AUTHENTIK_API_TOKEN
      remoteRef:
        key: queenbee/AUTHENTIK_API_TOKEN
