apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: 0.138.0
    helm:
      valuesObject:
        global:
          storageClass: local-path
        clickhouse:
          persistence:
            size: 30Gi
          resources:
            requests:
              cpu: 300m
              memory: 2Gi
            limits:
              memory: 4Gi
          zookeeper:
            persistence:
              size: 5Gi
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
        signoz:
          ingress:
            enabled: true
            className: internal
            hosts:
              - host: signoz.login.no
                paths:
                  - path: /
                    pathType: Prefix
                    port: 8080
            tls:
              - hosts:
                  - signoz.login.no
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
        otelCollector:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
