apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beehive
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: beehive-secrets
  data:
    - secretKey: AUTHENTIK_CLIENT_ID
      remoteRef:
        key: beehive/AUTHENTIK_CLIENT_ID
    - secretKey: AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: beehive/AUTHENTIK_CLIENT_SECRET
