apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
spec:
  provider:
    onepasswordSDK:
      vault: 65vzopwm2jr3kfdmqydms7vhla # TekKom-Secret-K8s-Onprem
      auth:
        serviceAccountSecretRef:
          name: 1password-token
          namespace: external-secrets
          key: token
