apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    chart: k8s-infra
    targetRevision: 0.17.0
    helm:
      valuesObject:
        global:
          clusterName: k8s-1
          deploymentEnvironment: prod
        otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
        otelInsecure: true
        presets:
          logsCollection:
            enabled: true
          hostMetrics:
            enabled: true
          kubeletMetrics:
            enabled: true
          kubernetesAttributes:
            enabled: true
          clusterMetrics:
            enabled: true
          k8sEvents:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
