apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-internal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 41.3.0
    helm:
      releaseName: traefik-internal
      valuesObject:
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: internal
        providers:
          kubernetesCRD:
            enabled: false
          kubernetesIngress:
            enabled: true
            ingressClass: internal
        service:
          annotations:
            metallb.io/loadBalancerIPs: 10.30.0.41
          spec:
            externalTrafficPolicy: Local
        ports:
          web:
            expose:
              default: true
          websecure:
            expose:
              default: true
            proxyProtocol:
              trustedIPs:
                - 10.10.0.21/32
            forwardedHeaders:
              trustedIPs:
                - 10.10.0.21/32
        accessLog:
          enabled: true
          format: json
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
